# 󱄠 󰵪 󰲑 󰕾 󰐊 󰎇󰁚󰁙 
app_refresh_duration_in_ms = 32
border_type = "Plain"
client_id = "d420a117a32841c2b3474932e49fb54b"
client_port = 8080
cover_img_length = 20
cover_img_scale = 1.0
cover_img_width = 20
default_device = "spotify-player"
enable_audio_visualization=true
enable_cover_image_cache = true
enable_media_control = false
enable_notify = true
enable_streaming = "Always"
explicit_icon = "(E)"
genre_num = 2
liked_icon = "♥"
login_redirect_uri = "http://127.0.0.1:8989/login"
notify_streaming_only = false
notify_timeout_in_secs = 0
page_size_in_rows = 20
pause_icon = ""
play_icon = ""
playback_format = """{status} {track} • {artists} {liked}\n{album} • {genres}\n{metadata}"""
playback_metadata_fields = ["repeat", "shuffle", "volume", "device",]
playback_refresh_duration_in_ms = 0
progress_bar_position = "Bottom"
progress_bar_type = "Rectangle"
seek_duration_secs = 5
sort_artist_albums_by_type = false
theme = "Catppuccin Mocha"
tracks_playback_limit = 50

[device]
name = "spotify-player"
device_type = "speaker"
volume = 95
bitrate = 320
audio_cache = false
normalization = false
autoplay = false

[layout]
playback_window_position = "Top"
playback_window_height = 0

[layout.library]
playlist_percent = 20
album_percent = 20

[notify_format]
summary = "{track} • {artists}"
body = "{album}"

